In [1]:
import torch
import torch.nn.functional as f
import torchvision

In [3]:
def kl_divergence(p, q):
    p = f.softmax(p, dim=-1)
    q = f.softmax(q, dim=-1)
    p = p.unsqueeze(1)
    q = q.unsqueeze(0)
    kl_matrix = (p * (p / q).log()).sum(-1)
    return torch.exp(-kl_matrix)

In [6]:
inputs1 = torch.randn((32, 512))
inputs2 = torch.randn((32, 512))
kl_divergence(inputs1, inputs1).shape

torch.Size([32, 32])

In [30]:
def kl_divergence(p, q):
    kl_div = F.kl_div(F.log_softmax(p, dim=-1), F.softmax(q, dim=-1), reduction='none')
    return kl_div.sum(-1).mean()



In [83]:
p = torch.randn((32, 512))
q = p

p = f.softmax(p, dim=-1)
q = f.softmax(q, dim=-1)

In [84]:
kl_mat = torch.zeros(32, 32)
for i in range(32):
    for j in range(32):
        kl_mat[i, j] = f.kl_div((p[i] + 1e-9).log(), q[j], reduction='batchmean')

In [85]:
p = p.unsqueeze(1)
q = q.unsqueeze(0)
kl_matrix = (p * (p / q).log()).sum(-1)

In [86]:
kl_mat

tensor([[-1.0475e-09,  1.9684e-03,  1.8026e-03,  ...,  2.0061e-03,
          1.8273e-03,  1.9455e-03],
        [ 1.8094e-03, -9.8646e-10,  2.0102e-03,  ...,  1.7264e-03,
          1.6433e-03,  2.0970e-03],
        [ 1.7965e-03,  1.9396e-03, -9.7498e-10,  ...,  1.8571e-03,
          1.9544e-03,  2.3418e-03],
        ...,
        [ 2.0161e-03,  1.7959e-03,  1.8703e-03,  ..., -9.6588e-10,
          1.9491e-03,  2.0898e-03],
        [ 1.8642e-03,  1.6683e-03,  1.9517e-03,  ...,  1.8599e-03,
         -9.5383e-10,  1.9502e-03],
        [ 2.0214e-03,  1.9536e-03,  1.9987e-03,  ...,  2.0871e-03,
          1.9228e-03, -9.3456e-10]])

In [89]:
torch.exp(-kl_matrix)

tensor([[1.0000, 0.3960, 0.3986,  ..., 0.3562, 0.3850, 0.3552],
        [0.3650, 1.0000, 0.3704,  ..., 0.3987, 0.4256, 0.3678],
        [0.3973, 0.3573, 1.0000,  ..., 0.3838, 0.3681, 0.3594],
        ...,
        [0.3580, 0.4132, 0.3864,  ..., 1.0000, 0.3859, 0.3435],
        [0.3924, 0.4311, 0.3676,  ..., 0.3686, 1.0000, 0.3736],
        [0.3693, 0.3418, 0.3015,  ..., 0.3430, 0.3684, 1.0000]])

In [20]:
torch.max(kl_div)

tensor(1.0000)

In [9]:
scores, labels = kl_div.topk(3, 1, True, True)

In [12]:
labels

tensor([[17, 19,  4],
        [17, 13, 19],
        [17,  1, 23],
        [17,  4, 19],
        [17, 23,  4],
        [17, 30, 16],
        [17,  4,  1],
        [17, 19,  4],
        [17,  4, 19],
        [17, 19, 30],
        [17, 19, 30],
        [17,  4,  1],
        [17,  4, 19],
        [17, 19,  4],
        [17, 19,  4],
        [17, 23,  7],
        [17, 23, 19],
        [17, 19,  4],
        [17, 19,  1],
        [17, 19,  4],
        [17, 23,  4],
        [17,  4, 19],
        [17,  4, 19],
        [17,  4, 19],
        [17, 19, 23],
        [17,  4, 19],
        [17, 19,  4],
        [19, 17, 13],
        [17,  4, 19],
        [17,  4, 19],
        [17, 19,  4],
        [ 4, 17, 19]])

In [95]:
targets = [0.22, 0.015, 0.3742, 0.395]
targets = torch.tensor(targets)

def func(x):
    return x + torch.log(-torch.expm1(-x))

func(targets)

tensor([-1.4021, -4.1922, -0.7900, -0.7249])

In [94]:
torch.nn.functional.softplus(torch.tensor(-1.4021))

tensor(0.2200)